use std::{
    fs::{self, File},
    io::{self, Write},
    path::PathBuf,
};

const DEFAULT_CONFIG_FILE: &str = "docs/config.toml";
const README_FILE: &str = "docs/REPO_README.md";
const README_DEST: &str = "README.md";

fn main() -> io::Result<()> {
    println!("cargo:rerun-if-changed={}", DEFAULT_CONFIG_FILE);
    println!("cargo:rerun-if-changed={}", README_FILE);

    let dest_path = PathBuf::from(README_DEST);
    let mut dest_file = File::create(dest_path).expect("failed to create readme file");

    let file_path = PathBuf::from(README_FILE);
    let mut file_contents = fs::read_to_string(file_path).expect("no repo readme file round");

    let default_config_path = PathBuf::from(DEFAULT_CONFIG_FILE);
    let default_config =
        fs::read_to_string(default_config_path).expect("failed to find default config");

    file_contents = file_contents.replace("{default_config}", &default_config);

    write!(
        dest_file,
        "
<!--
DON'T CONTRIBUTE TO THIS FILE!
This file is generated by `build.rs` from `docs/REPO_README.md`, which is the file to edit to \
         change the README.
-->\n
{}
",
        file_contents
    )?;

    Ok(())
}
